version: '3'
services:
  redis-server:
    image: 'redis'
    command: redis-server --protected-mode no
  visits-nodejs:
    build: .
    ports:
    - "8082:8082"
    restart: always
  simplewebapp-nodejs:
    image: 'simplewebapp-nodejs'
    ports:
    - "8081:8081"